----
- name: "Install Node.js"
  become: true
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    source ~/.profile
    nvm install 13.8.0
    nvm use 13.8.0
    source ~/.bashrc

- name: "Install npm"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes    

    
- name: "Install PM2"
  npm:
    name: pm2
    global: yes    